services:
  ai-secretary:
    build: .
    volumes:
      - ../:/usr/src/app/
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - secretary-ai-network
  ai-secretary-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/usr/src/app/
    env_file:
      - .env
    networks:
      - secretary-ai-network
    command: npm run dev
networks:
  secretary-ai-network:
    driver: bridge
